export default {
    media: 'breakpoints',
    breakpoint: 'breakpoints',
    space: 'space',
    color: 'colors',
    font: 'fonts',
    fontSize: 'fontSizes',
    fontWeight: 'fontWeights',
    lineHeight: 'lineHeights',
    letterSpacing: 'letterSpacings',
    borderWidth: 'borderWidths',
    radius: 'radii',
    shadow: 'shadows',
    zIndex: 'zIndices',
}